# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clip < Formula
  desc "Upload your clipboard for sharing"
  homepage ""
  version "0.5.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bemoty/clip/releases/download/v0.5.1/clip_0.5.1_darwin_amd64.tar.gz"
      sha256 "d239a7cae60b9125b4fc51d6ac2494b5e86c34e012936e905d0d2496a0b68879"

      define_method(:install) do
        bin.install "clip"
        man1.install Dir["man/clip*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bemoty/clip/releases/download/v0.5.1/clip_0.5.1_darwin_arm64.tar.gz"
      sha256 "d4950a70abc8bb2daceb1829be73f7ad7219192e3ed4ea5c0cbe3ff1d28953fe"

      define_method(:install) do
        bin.install "clip"
        man1.install Dir["man/clip*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bemoty/clip/releases/download/v0.5.1/clip_0.5.1_linux_amd64.tar.gz"
      sha256 "f237a85ab046bb2517673bf5ec145469b3f7118f6b8e660e3c7f9805acfd7f2f"
      define_method(:install) do
        bin.install "clip"
        man1.install Dir["man/clip*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bemoty/clip/releases/download/v0.5.1/clip_0.5.1_linux_arm64.tar.gz"
      sha256 "25f79cec11ec985ec1bddad7d5967cbf60d45501201998ffd01255bdec64ba92"
      define_method(:install) do
        bin.install "clip"
        man1.install Dir["man/clip*.1"]
      end
    end
  end

  test do
    system "#{bin}/clip version"
  end
end
