# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clip < Formula
  desc "Upload your clipboard for sharing"
  homepage ""
  version "0.4.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bemoty/clip/releases/download/v0.4.1/clip_0.4.1_darwin_amd64.tar.gz"
      sha256 "4f73f948f4fa99207160f41f7aecd490f733a31fc82902232a255e7da575d64b"

      define_method(:install) do
        bin.install "clip"
        man1.install Dir["man/clip*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bemoty/clip/releases/download/v0.4.1/clip_0.4.1_darwin_arm64.tar.gz"
      sha256 "1f1a0308ca5c4ae5e6fac7736e483ec842fab04acf10b80282899fb24b0d4b46"

      define_method(:install) do
        bin.install "clip"
        man1.install Dir["man/clip*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bemoty/clip/releases/download/v0.4.1/clip_0.4.1_linux_amd64.tar.gz"
      sha256 "cf7b00f6fdcc9f50ea21afa1332f77e000ad0dd03254e90cb0c7bdd2902af328"
      define_method(:install) do
        bin.install "clip"
        man1.install Dir["man/clip*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bemoty/clip/releases/download/v0.4.1/clip_0.4.1_linux_arm64.tar.gz"
      sha256 "f1c1957836d4f45fbe10e1bf13885082cddba945534bc841a96614e15a6bc4cf"
      define_method(:install) do
        bin.install "clip"
        man1.install Dir["man/clip*.1"]
      end
    end
  end

  test do
    system "#{bin}/clip version"
  end
end
